### ISSUE TITLE
Exception handling in makedirs - compute_stability_corr.py

### ISSUE THREAD

**Issue by raihaan** [CoBrALab/cobra-nmf#5]
Line 17: if statement to check existence of output dir and then makedir, coupled with script instructions to run per granularity raises possibility of if not statement evaluating to true but directory being made shortly after, a la https://stackoverflow.com/questions/12468022/python-fileexists-error-when-making-directory

**Comment by gdevenyi** [comment]
https://github.com/CoBrALab/MAGeTbrain/blob/simplified-labelmask/bin/mb#L746-L756

**Comment by raihaan** [comment]
Merci Gabe. closed with 3d8509884b7c73dc7abeefcdf473008587a9a0aa
