### ISSUE TITLE
mat_to_brainview.py name error in argparse

### ISSUE THREAD

**Issue by justineziolkowski** [CoBrALab/cobra-nmf#9]
Line 38:
NameError: name 'out_dir' is not defined

'out_dir' also used on lines 70 & 94

**Comment by raihaan** [comment]
tnx, just pushed a change. run git pull to grab the update, let me know how it goes

**Comment by raihaan** [comment]
fixed with 98c33a4a37826a5e25223e94b6d5bc4858676ae4
